import { compressSync, type SkinData } from '@sonolus/core'
import fs from 'fs-extra'
import path from 'node:path'
import { buildSkinData, buildTexture, packSprites } from './atlas.js'
import { getDirectionalResources, buildDirectionalSprites } from './resources/directional.js'
import type { DirectionalResources } from './resources/directional.js'
import { getFieldResources, buildFieldSprites } from './resources/field.js'
import type { FieldResources } from './resources/field.js'
import { buildNoteSkinSprites, getNoteSkinResources } from './resources/noteskin.js'
import type { NoteSkinResources } from './resources/noteskin.js'
import { resize, toSharp } from './image.js'
import type { GenerationPlan, ImageAsset, SpriteAsset } from './types.js'

export type GenerationResourceCache = {
    notes: Map<string, Promise<NoteSkinResources>>
    directionals: Map<string, Promise<DirectionalResources>>
    fields: Map<string, Promise<FieldResources>>
}

export function createGenerationResourceCache(): GenerationResourceCache {
    return {
        notes: new Map(),
        directionals: new Map(),
        fields: new Map(),
    }
}

export async function generateSkin(plan: GenerationPlan, outputRoot: string, cache = createGenerationResourceCache()): Promise<void> {
    const name = skinName(plan)

    const [noteResources, directionalResources, fieldResources] = await Promise.all([
        getCached(cache.notes, `${plan.rhythm.server}:${plan.rhythm.id}:${plan.mode === 'habahiro'}`, () => getNoteSkinResources(plan.rhythm.id, plan.rhythm.server, plan.mode === 'habahiro')),
        getCached(cache.directionals, `${plan.directional.server}:${plan.directional.id}`, () => getDirectionalResources(plan.directional.id, plan.directional.server)),
        getCached(cache.fields, `${plan.field.server}:${plan.field.id}`, () => getFieldResources(plan.field.id, plan.field.server)),
    ])

    const sprites: SpriteAsset[] = [
        ...buildNoteSkinSprites(noteResources),
        ...(await buildDirectionalSprites(directionalResources)),
        ...(await buildFieldSprites(fieldResources)),
    ]
    assertUniqueNames(sprites)

    const { width, height, packed } = packSprites(sprites)
    const dataObject = buildSkinData(width, height, packed)
    const data = compressSync<SkinData>(dataObject)
    const texture = await buildTexture(width, height, packed)
    const thumbnail = await buildThumbnail(
        noteResources,
        directionalResources.sprites.get('note_flick_l_3')!,
        directionalResources.sprites.get('note_flick_r_3')!,
        fieldResources.stageImage,
        fieldResources.lineImage,
    )

    assertNoJudgeSprites(dataObject)

    const outputDir = path.join(outputRoot, name)
    await fs.ensureDir(outputDir)
    await fs.writeJson(path.join(outputDir, 'item.json'), buildItem(plan), { spaces: 4 })
    await fs.writeFile(path.join(outputDir, 'data'), data)
    await fs.writeFile(path.join(outputDir, 'texture.png'), texture)
    await fs.writeFile(path.join(outputDir, 'thumbnail.png'), thumbnail)
}

function getCached<T>(cache: Map<string, Promise<T>>, key: string, getValue: () => Promise<T>): Promise<T> {
    const cached = cache.get(key)
    if (cached) return cached

    const value = getValue()
    cache.set(key, value)
    return value
}

export function skinName(plan: GenerationPlan): string {
    return ['bandori', plan.rhythm.id, plan.directional.id, plan.field.id].map(slug).join('-').toLowerCase()
}

function buildItem(plan: GenerationPlan) {
    const title = `${plan.rhythm.title} / ${plan.directional.title} / ${plan.field.title}`
    const description = [
        'Generated by sonolus-bandori-skin-generator.',
        `Mode: ${plan.mode}`,
        `RhythmSkin: ${plan.rhythm.id}`,
        `DirectionalFlickSkin: ${plan.directional.id}`,
        `FieldSkin: ${plan.field.id}`,
    ].join('\n')
    const descriptionZhs = [
        '由 sonolus-bandori-skin-generator 生成。',
        `模式：${plan.mode}`,
        `RhythmSkin：${plan.rhythm.id}`,
        `DirectionalFlickSkin：${plan.directional.id}`,
        `FieldSkin：${plan.field.id}`,
    ].join('\n')

    return {
        version: 4,
        title: {
            en: title,
            zhs: title,
        },
        subtitle: {
            en: 'BanG Dream! Girls Band Party!',
            zhs: 'BanG Dream! 少女乐团派对！',
        },
        author: {
            en: 'WindowsSov8forUs',
            zhs: 'WindowsSov8forUs',
        },
        tags: [],
        description: {
            en: description,
            zhs: descriptionZhs,
        },
    }
}

type NoteThumbnailResources = {
    sprites: Map<string, ImageAsset>
}

async function buildThumbnail(notes: NoteThumbnailResources, directionalLeft: ImageAsset, directionalRight: ImageAsset, stage: ImageAsset, line: ImageAsset): Promise<Buffer> {
    const width = (480 * 1.35) / 0.875
    const height = (width * line.height) / line.width
    const resizedLine = await resize(line, Math.round(width), Math.round(height), 'lanczos3')
    const lineLeft = Math.round((width - 480) / 2)
    const croppedLine = await toSharp(resizedLine)
        .extract({ left: lineLeft, top: 0, width: 480, height: Math.round(height) })
        .png()
        .toBuffer()

    const thumb = {
        data: Buffer.alloc(480 * 480 * 4),
        width: 480,
        height: 480,
        channels: 4 as const,
    }

    const composition = async (image: ImageAsset, x: number, y: number, w: number, h: number) => {
        const resized = await resize(image, Math.round(w * 80), Math.round(h * 80), 'lanczos3')
        return {
            input: resized.data,
            raw: { width: resized.width, height: resized.height, channels: 4 as const },
            left: Math.round(x * 80),
            top: Math.round(y * 80),
        }
    }

    return toSharp(thumb)
        .composite([
            await composition(stage, 0, 1.5, 6, 4),
            { input: croppedLine, left: 0, top: 440 - Math.round(height / 2) },
            await composition(requireThumbSprite(notes, 'note_normal_3'), 0.45, 0.2, 1.5, 0.75),
            await composition(requireThumbSprite(notes, 'note_skill_3'), 2.25, 0.2, 1.5, 0.75),
            await composition(requireThumbSprite(notes, 'note_flick_3'), 4.05, 0.2, 1.5, 0.75),
            await composition(requireThumbSprite(notes, 'note_long_3'), 0.45, 1.0, 1.5, 0.75),
            await composition(directionalLeft, 2.25, 1.0, 1.5, 0.75),
            await composition(directionalRight, 4.05, 1.0, 1.5, 0.75),
        ])
        .png({ compressionLevel: 9 })
        .toBuffer()
}

function requireThumbSprite(notes: NoteThumbnailResources, name: string): ImageAsset {
    const sprite = notes.sprites.get(name)
    if (!sprite) throw new Error(`thumbnail missing sprite: ${name}`)
    return sprite
}

function assertUniqueNames(sprites: SpriteAsset[]): void {
    const names = new Set<string>()
    for (const sprite of sprites) {
        for (const name of sprite.names) {
            if (names.has(name)) throw new Error(`duplicate sprite name: ${name}`)
            names.add(name)
        }
    }
}

function assertNoJudgeSprites(data: SkinData): void {
    const found = data.sprites.find((sprite) => sprite.name.toLowerCase().includes('judge'))
    if (found) throw new Error(`unexpected judge sprite: ${found.name}`)
}

function slug(name: string): string {
    return name.replace(/[^a-zA-Z0-9_-]+/g, '_')
}
